version: '2'
services:
  nodered:
    container_name: nodered
    depends_on:
        - grafana
    image: nodered/node-red:latest
    environment:
        - TZ=Europe/Brussels
    ports:
        - "1880:1880"
    volumes:
        - ./nodered-provisioning/:/data
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=iotlab
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning      
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  grafana_data: {}
  influxdb_data: {}
  nodered_data: {}
