version: '2'
services:
  nodered:
    container_name: nodered
    depends_on:
        - grafana
    image: nodered/node-red:latest
    environment:
        - TZ=Europe/Brussels
    ports:
        - "1880:1880"
    volumes:
        - ./nodered-provisioning/:/data
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=iotlab
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning      
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - '9443:9443'
    volumes:
      - portainer_data:/var/lib/portainer
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  mqtt:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto-provisioning/data:/mosquitto/data
      - ./mosquitto-provisioning/log:/mosquitto/log  
      - ./mosquitto-provisioning/config:/mosquitto/config     
    environment:
      - MOSQUITTO_LOG_LEVEL=info  # Aggiunta variabile di ambiente per il livello di log      

volumes:
  grafana_data: {}
  influxdb_data: {}
  nodered_data: {}
  portainer_data: {}
  mqtt_data: {}
